// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models
{
    public partial class TAdmin
    {
        /// <summary>
        /// 内测码
        /// </summary>
        public string Ano { get; set; }
    }
}