// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models
{
    public partial class TBorrow
    {
        public int Bid { get; set; }
        /// <summary>
        /// 借用人
        /// </summary>
        public int? Uid { get; set; }
        /// <summary>
        /// 物品
        /// </summary>
        public int? Oid { get; set; }
        /// <summary>
        /// 归还日期
        /// </summary>
        public DateTime? Retime { get; set; }
        /// <summary>
        /// 0正在审核，1已通过，2未通过
        /// </summary>
        public int? Pass { get; set; }

        public virtual TObj OidNavigation { get; set; }
        public virtual TUser UidNavigation { get; set; }
    }
}