// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WinFormsApp1.Models
{
    public partial class TObj
    {
        public TObj()
        {
            TBorrow = new HashSet<TBorrow>();
        }

        public int Oid { get; set; }
        /// <summary>
        /// 物品名
        /// </summary>
        public string Oname { get; set; }
        /// <summary>
        /// 物品种类(1书，2体育用品，3工具，4电子产品，5乐器，6小玩意，7其他)
        /// </summary>
        public int? Ocate { get; set; }
        /// <summary>
        /// 物品图片
        /// </summary>
        public byte[] Oimg { get; set; }
        /// <summary>
        /// 最长借用时间(天数)
        /// </summary>
        public int? Oretime { get; set; }
        /// <summary>
        /// 物品状态(0待审核，1可借用，2已被借用，3超出归还日期)
        /// </summary>
        public int? Ostatus { get; set; }
        /// <summary>
        /// 物品所属人
        /// </summary>
        public int? Uid { get; set; }

        public virtual TUser UidNavigation { get; set; }
        public virtual ICollection<TBorrow> TBorrow { get; set; }
    }
}